apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: belovr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
      app.kubernetes.io/instance: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
        app.kubernetes.io/instance: auth
        app.kubernetes.io/component: microservice
        app.kubernetes.io/part-of: belovr
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: auth
          image: ghcr.io/nicolasdemol/auth:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: belovr-common-config
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secrets
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
