apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: belovr
    belovr.io/environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
      app.kubernetes.io/instance: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
        app.kubernetes.io/instance: auth
        app.kubernetes.io/component: microservice
        app.kubernetes.io/part-of: belovr
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: auth
          image: ghcr.io/nicolasdemol/auth:c1dda91f1ee168c4e31544fc0d64bb95139f1a1b
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: belovr-common-config
            - configMapRef:
                name: auth-config
            - secretRef:
                name: belovr-auth-secrets
            - secretRef:
                name: keycloak-auth-secrets
            - secretRef:
                name: belovr-rabbitmq-secrets
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: belovr
    belovr.io/environment: prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
