apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/name: content
    app.kubernetes.io/instance: content
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: belovr
    belovr.io/environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: content
      app.kubernetes.io/instance: content
  template:
    metadata:
      labels:
        app.kubernetes.io/name: content
        app.kubernetes.io/instance: content
        app.kubernetes.io/component: microservice
        app.kubernetes.io/part-of: belovr
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: content
          image: ghcr.io/nicolasdemol/content:e28b9668aaa00807767dcb3e38506b665f5f9e1d
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: belovr-common-config
            - configMapRef:
                name: content-config
            - secretRef:
                name: belovr-auth-secrets
            - secretRef:
                name: belovr-rabbitmq-secrets
            - secretRef:
                name: belovr-r2-secrets
            - secretRef:
                name: content-db-secrets
            - secretRef:
                name: content-cloudflare-secrets
          ports:
            - name: http
              containerPort: 4100
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: content
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/name: content
    app.kubernetes.io/instance: content
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: belovr
    belovr.io/environment: prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: content
    app.kubernetes.io/instance: content
  ports:
    - name: http
      port: 4100
      targetPort: http
      protocol: TCP
