apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/name: image
    app.kubernetes.io/instance: image
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: belovr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: image
      app.kubernetes.io/instance: image
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image
        app.kubernetes.io/instance: image
        app.kubernetes.io/component: microservice
        app.kubernetes.io/part-of: belovr
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: image
          image: ghcr.io/nicolasdemol/image:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: belovr-common-config
            - configMapRef:
                name: image-config
            - secretRef:
                name: image-secrets
          ports:
            - name: http
              containerPort: 4600
              protocol: TCP
