apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/instance: payment
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: belovr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
      app.kubernetes.io/instance: payment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment
        app.kubernetes.io/instance: payment
        app.kubernetes.io/component: microservice
        app.kubernetes.io/part-of: belovr
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: payment
          image: ghcr.io/nicolasdemol/payment:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: belovr-common-config
            - configMapRef:
                name: payment-config
            - secretRef:
                name: belovr-auth-secrets
            - secretRef:
                name: belovr-rabbitmq-secrets
            - secretRef:
                name: payment-db-secrets
            - secretRef:
                name: payment-shared-secrets
            - secretRef:
                name: payment-provider-secrets
          ports:
            - name: http
              containerPort: 4400
              protocol: TCP
