apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../argocd/project
  - ../../../argocd/project/prod
  - ../../../infrastructure/namespace
  - ../../../infrastructure/network/base
  - ../../../infrastructure/dev
  - ../../../infrastructure/network/dev
  - ../../../infrastructure/argocd/dev
  - web-ingress.yaml
patches:
  - path: public-ingress-backends-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: belovr-main-ingress
  - path: web-ingress-detach-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: belovr-main-ingress
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: belovr-platform
    patch: |-
      - op: add
        path: /spec/destinations/-
        value:
          namespace: argocd
          server: https://kubernetes.default.svc
labels:
  - pairs:
      belovr.io/environment: prod
