apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-wildcard-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/part-of: belovr-platform
spec:
  secretName: lab-tls-secret
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  commonName: "*.lab.belovr.com"
  dnsNames:
    - "*.lab.belovr.com"
