apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: belovr-cors
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/part-of: belovr-platform
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - DNT
      - Keep-Alive
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Range
      - Authorization
    accessControlAllowMethods:
      - GET
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS
    accessControlAllowOriginList:
      - https://app.belovr.com
    accessControlMaxAge: 1728000
    addVaryHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: belovr-upload-100m
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/part-of: belovr-platform
spec:
  buffering:
    maxRequestBodyBytes: 104857600
