---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-secrets
  namespace: belovr
spec:
  encryptedData:
    ADMIN_TOKEN: AgCfRbqSv8FLzaluZZFSA3zKYpZ4ViB9unY5imCUIXwpOTpFc+wYz2ckXtWXhzHEcJTLcs+K24G0EAzLztuS2ReY2mE9wk1H2nc/3qIUb1FmM9EEuwi217sZRbimwztVqiwiPC4Q9ogQAOGLzHiPzKVNnS7KhuDljh+IUFsK5I5+XUNQ7xT6dRA9DEIw9fVKAUfevc9F1Ok2arJYcS9+kLm9QJT89wA7BdUXhFPjozNaiFl+VWJ9ilKcIk1W9edu8Ua3/Sr9VzaP2V6ehRTJQhJ8dU1guSwVmDb+tE/1j63KKi7WYViDTDRDWtNW5WmJjyUqyGu1YMoXTyPDhxPhRSiARAmKyuFRWT5CFptDpHPDvwvLbpnf6X+l3VTjYaBgpBTG7y7SBCDlRmiRbpHZNdfm+RimRaP0m0WDHFEnGIs/KOrVIoVHpy9dogvpoxfOpRmeG9CMCE8RFaJkIMRNCkylAX+Bmci6Tp7Y0hnXPmKmXrOC1XK4q+U+tj9T0pJAX5ugBIpTfYo21kjeU42kL9ueh8MIINdGXVwAbBtV5uKeaCNy0veWcbt75YTrayc8dZRwGyJA7/1KT/BgxFdmDQoP1mnPYGOi9SKS9zIYmJ1sQMOPLahpLn1AwSVXqMeN7teLBMqtClxaCU0FdFqIyJb9RSTca/gmb95Ghe2hygQ8/p329S9XVxuRZ5QqhTI4GCB7z5CIiyb0EjljG3WG/MzZLfu0sNSiKs23xrpAgIIjtMI7T0TSv54BjJE8/oL65aItFlMTjY7gjcwvHZ8bzwKc
  template:
    metadata:
      name: ai-secrets
      namespace: belovr
