---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: belovr-auth-secrets
  namespace: belovr
spec:
  encryptedData:
    BELOVR_JWT_SECRET: AgCXsaSfDPttW2tndUAOk4fSOOIT8pKWjalJWsXsOUDJa0xzC4BhXarOPLQhRQKs5elGedT1qYlMYKnXKq/7IarYVnksRTsLqvYFbnkM3UBN3G3ChR7OPM124Uftssyq4HK/XTgcAukKj0duJpQvakCVbvANgr41iQbhrOoPw1YzThg0diNyI7NaKe/FGLSD3J8NleqgAFH7RjXlp9UV/qVlHlVM9E9gm4yahW0ktrAbRbsfRpsbLAxaw0lHK2m/Lw1UFspC7NtKIbYCJbVDUsdt+rr2gKWjfmwQCQvKNMedAL0/aDGA3ImNzSM6CdAeMUmKvtzMBbOKy8thx0mo9OA+3tL9GsTRZO8i9kBG+IDTn5G6FNdPfZBWwfSVee11j/81RgmTTaQH530IGQtdMYMG9znQ9dUKhLh3U4LqwDGgd59mBXOPeUZ6u0MiM3D+FEuVMcLP9DRP64Zer1NxMaOMVYpIq+6sK47rupGeaTzKyqfbO58ZIpPsUpUMQ3izRi8kGfDmHcHD+xV3wBnv9DcgzIOSWLkgLR8oVdIBlLhVJ9nB8JavFKs1mxTtL5ql8HpmLbdU26WM0Rr/k7CzdrWhrI6VgRCskF3j0oGZKaSKODM60QmAZ0ZsqP8cYKZGYnSydKab4aTGoyHkQ0HSy+lqYuSrfWVlhSxSYfXSU69sI5Ni555vcnuJcryvK9CpPIQjmdxnMhVIMZL6pLqX2gJGnL9UmTenysa1gxQq8FrYVfYlFNcdOKhrWmwZ7Xx/plYtFM3iRyGX1dK4n1qpt3MK
  template:
    metadata:
      name: belovr-auth-secrets
      namespace: belovr
