---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-keycloak-secrets
  namespace: belovr
spec:
  encryptedData:
    AUTH_KEYCLOAK_SECRET: AgBtD5n81KhADcunafc+eGyzSEuaNl89NobBeqy5ioAhC9GL3+GrrnKRzZLR4u4u/2hU+kE70F2nY4OG6Js5opzJboGfc0qU7XuXfgvTPaGd/mJXcV9v3tjlNRiOjW2r79R45ImCpmJDPewyEtmJiu/kbnVyW4vsKyza3OlppDlbXh6AGiIKBd0G3F+aPrlOm6yD+swOWtwUF18cbckw07TaNq66O4JJ/OgrQ0oGJhS2n6TOWW4OF8wrKbugkuop3QsFlAhUScfxiwed2rPy+IVhQqOb9ga2EwtUSDPhGnomKt89p5wVi6uTpAtOBQA57N+b5L5MkgkizfVDAqProkWYGCxKeE2pKyTPBj+Iba0sw5tz9trtw/sjKwlasamC+cLz9oz00tNLTORonkFtzrMV28x9HRWusUjFrbXtqdQdidigYr6tYPo4dwrfSJWymuKaMUrFAezyn8yKFX/8u7wR+ypzcIcNkpHrr9DAQliT1882lMGWjONls+IKMos1kWlxEwqwn3PRgJkvleZCEFQPm21DlbS+fqcVYw8zYxFCRaB2h7SgtuQTotBUC8du861LC8ggkMbt8j7xiXR/2gfEkCjaJN/IxmfF7+trB8lO5tlxCBZkqqiblUkgB2UimmqyFLyojEvLszDSLiIdKM8qgLpgTMNTHl6D0g4bD9pa2VHHRm7U3jD6WC+4ehHgCDtyRq2Q/xCDbiY1MDURdRusLmSXxAC4E6vkoUHDMFxRng==
  template:
    metadata:
      name: auth-keycloak-secrets
      namespace: belovr
