---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-keycloak-secrets
  namespace: belovr
spec:
  encryptedData:
    AUTH_KEYCLOAK_SECRET: AgBS10bBgmED14wvlaUIwhTX/Wzpy3NP8SAnLyJSGhPyan5P88vaXjvPFonOpA1wcvbDiCZbvqeTi1TLQaEh0qffAvlea9yVms+1dokeRZQGqEt5F8h2FPrKNRdcY8FDJ31ks4Mf1v3GbFoVB68hHaiI+Jrbucky2ncx2yk7+s2QYXppVICrGojRZ0JKWMX0d5XlIeD2J21RypcnBbQUpjAV/vDgnDtr13KTsvrwF518ujoUajo7WNDOz2jN4mXmgCfIcK7KqcX46xBQ107U6TSy1SPsexn6Iu6crhwBGQMSp2npQBS1NPF7mkEg9xswjGEfS1tY4EufPENIasOi8L4ZHKXNyqp5MGQSeVxz0byJCrP4Kbent4arfGonbKErJ1Gu/ZQAeVXuL8jViqPJ5T6Ul6jIDtbOEo3oURpovLia2f1KphqJMOM5yfoB/lynWurJnAyUQcOUjSP78yTDflfO0BZorRxBdoLeJMjJwZaIZEBR3/z2KIrPHMO1x/+ayJVKb0isSAWaHw4l0ivoFBiH1XRiQi6E6SuJb7L5a9rArAoSkeE1nP7c6qalPZsWxvp1x28/y9AKCOT1Wv5LLzJMbTheof3/ZMHasyoBAPPARp3wO88tB94xMxC7w02uYA/FvcmFVxEZY4heQqIRPg+D2T5TpoYLH11yOyntAjG/YbiDySh+PNmxPo47iJCu8kpL2xk6htWq4q88PHMLrP+JHSKxkJRcJlWm/uTXHYYTtw==
  template:
    metadata:
      name: auth-keycloak-secrets
      namespace: belovr
