---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chat-db-secrets
  namespace: belovr
spec:
  encryptedData:
    CHAT_DB_PASSWORD: AgBmhSjzyHaUTwhseiZT82Iyqz4xhGMseED6xBslL3N4QcqPWoIeHaDhuNGWDzy6uIr5uxziafZqe22ccEAnZZ8T+pJKA58L6fryKL1oAvV5Y+UMxKXVlz3V1WekRaQtNQJb3gqv6Jel2WLutWIY0kxLqUtaYe/qYRo16Z7OmLdwdduEalGZw1EhWRiGqy/+dvcbJPbr8vq5IhBLs5A3jWmsQnh2i4LKoq5bbgbpNODqOkFMiMA7FULYcjSwxRv6wXN3AQ/y/OTUmyjU/zZxXElmvM23LmT74U6rzDjeii2I2nPe7pL96NlPORF1xWFcUP/yRthkDD8vF3qhFasLuPhzP3GKk5UjW07IjP7GgNZiJOXYntzJsSDgPnGXAKhup9HrXoOKtdxJxCHUqGfmWOjawQ2tPR/gQ5uPvJGEL1IlsVRBIaqG03xnHitYKkEg+r0wjyw+pl0xzyHZZway9vyjN6EYWuZuvbUnhvWBeJTb2sg6Ct9BIK3KxHwhKaAyFV22SjItFrHKCLEPz3PyNRVGxoaYUeAo942oIMV6I8XEfMIyRCw3lSuQcnvG9aiJkNaOUBPNm/74X/eUA1MYpdGuRgwn+W/IeRhqGGp82mVbYHUw1HTYjo80uo8Xrcb7yRldafX4TtKB8mAuHONS1HrNaiYP+m+A241xk4VRNJPksFs1arTIU81d0Mgf14ayv3dB+i5D7oeW1HdgBpBAc2WwW+K+CcLhgQ4kZ83tX1Y4bpJnHGZqQ/6Ou6R+QpXjRtsWy1I0LpM6/ewXPyyBhh5N
  template:
    metadata:
      name: chat-db-secrets
      namespace: belovr
