---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: content-db-secrets
  namespace: belovr
spec:
  encryptedData:
    CONTENT_DB_PASSWORD: AgARNJKtwJmN+a1cYQyIw7HbqTeUsPC2lob0a2Xmuo6Y4aKIv95WfyIk0mOKx7y1wMWMKC7YM2A78orESDWcLHM/0hEZL8w16M9WUGCXa82z9w3Vcc1wdu8ztSxQOeFJeO90elzz1LCtQULlrDu49iSnhHHzn75sVNATeeKBy5obOYrSdO2Shydpl+u8SGmjuwfkdzRP9INaRr3LYiOQKA71GACYd7nILI0moEq5PeWbc14HKywhngtbjiX+ReOp5hipHGD2n/wuHKN9kTftL/ZOe8Hw02VC8t9XMnaS87Wqneb0TNIoj5Fe+lVdb2iWi/gVNeMDDD6Hv+po6gkTVXmES+xKRIe9hlbTYPQTtWUTpCpM28doz8rYqMwnFgu3krQouPt9EMy0C0GcG8t8xPOnMX1Yhi05c0ED9ncLgxO5hoL/GOQ6gY9Ctm1029FzxGCqUz53HE5naw8WqP81c6OnQsimNz6EBYOxe4/YeGvGnu0lhtXVeTD61qOBNcDMpovkfDf8r44N2R6PRvlT5S11lXLRDtaJv/ylKPuvMRAeanKyj3Tuj0bQBvIdSResyKEQI8JK+hJmnnSJLDICd2v7KKdC1Zmd7XfZ+SM6eDJBTAUhrI0RQrGO/xg8W/EWf2t4CrH3I2rJBwFlP9MfZJUUyBwv0U3mhucSCzL7uH2uCxKMT3de+MGziVAWXUXLLRla/JW6MZVn+0vHZ8qeZhYLHhK6zBJMwCKQM85oQ6ER/x4uc+YI6I5liCHGZVWDBMg/Yq3uCBsDnjgEuy617M58
  template:
    metadata:
      name: content-db-secrets
      namespace: belovr
