---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secrets
  namespace: observability
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgBLFrXk8eSX/wcPQbep5ssIQVLklYXHDsfIwK0XqfXvy/iRr2j5Om3in6c3jYDgggSpgrd6wawMvMDAKbxqSwNhmhRoHQesBaWLP+aTx0m5u2YYm9QkJ7WEy4dneT127qtD3OFYeyDrUj6KHI9j10aZp4j0iQ/NdgKvp67KcKv8/ArC9cUcs2G+z3QL54lMj2IRU0R2YaldkZOXTu8+F3BQPNGsPWTiO4kb6ntCelLlbPcpZSSwAqealcIUtJ+paUBWT5LgOs1aDN1+xmyeVWU5UjxaGw9mWZC37GOkJLg0lSKrXuAsCByqcI0d77x3huL1h9bph0/fU5I1K3VVEZeOzAChy7UZLGyM+mej0ICZNT4HkpmA+dfWPtcaopvea4uyhAeDC50r2HSwcJbtR2Q6dS0Vh/jh/2tIIalxdc4RMgCw+SUP64SjVyG6OULscm4u0lwtvffwVMBCXWiZrLj8kYfDd3cID9jOQTEQovAb3oteIqJePyLlotpvOmgLcxLGuK20Zx/9w81Q7PPPr0Mrv+qbMfMnfmDka/Ybq5/ob1QHOJAuLhYsk35z6gwj0HNVEEhMUL8KqyRVCoefojRGEgAX5yXAxWFbHbDLe0FOAgiiVz5WwjQFG2IZH3Lr2TemiBfD4L8NY5FMXI7NGMbVR8etsLIWDzRiyOvkYVb6ijUX6yk2QzPf2z9dgwywEg9ifYJxzrnAOIq983MXHGy5cOVymXBaJlx0rvkbHDXT8Pa12cnPSZBFYn0lYiH3DbgE64fAJhpFy2IRCg0CSGdr
    GRAFANA_ADMIN_USER: AgAQuKVtSM1XUitdGDcTVObEPu8aFHYPJbBY91VhUHcd67Sf8kz1hiJnrJftTxXVu4op9D9s4/u8BnVhocmuIVFO/WopeQBTadwZmQKQOdVboVK5PBIv+wvDcaJF38d4BmK85xYOTlfpg3brmqa/qsq64E3mcpoAkPq3ma/kRwpCXz07gTxvRdGygWHfMM4H4Uw/YzFRzhuDWXxJaE03hDsPStAruSoqBg5OLvP7td/kissf7ggsVsuTulQXIv4Jf8JXO7/TWc5xSaT13xt01A4MtGHeDKDm8IGYxvDQhLkl1uRiHHdYTXZGEURwA1APVOq0Exrna04LGENyuSVf+oUvg2cAMUeMNQYT4AnCaWweU0Qdj5q5MfTHpoX/lv4e0piFbDdUuzbQKqpAQu8cLEhkfjtzVRvkU1201R73hH8u0T2JpIcDpyEc2rwioTgzO4pMUJOYmeCc5mkoOOLthhpkq51FB+PigQIFwddYX/tdxWZF29ReS5dCpunZhXglf7mzjNnqF8nV6+df+mREsffGx/0E4L8SmiTPqKUlW9zR4eYBEzsgzfE/QZzMeIxzjBnkN090I9R8mRF58+rTf7PKlJmbhSodazCGl9d4yYvu98BV6mEu0UFhJ1PzCf78ZZKnvXTIO9dFYrP8/4MtkVckqyTjBrTOvJUyUPlwRSLb8PPwcabYqdI/2HABMURengXy6yxRGA==
  template:
    metadata:
      name: grafana-admin-secrets
      namespace: observability
