---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secrets
  namespace: belovr
spec:
  encryptedData:
    KEYCLOAK_DB_PASSWORD: AgBXLV3rrlA791N/y5RHQdxLsfvIswsVHrdDjvgwwxc3yH7N3JzaVPIv0ieUxr2B+hOqdgl3REOlcWCwN5LaUWTpQYjXeHRuQCNulxAL2TY1dy0FDPzHvGuBCaMZkVLCiEMRgHRt+9OmApfQIzj01SPpgzxAXKmQDB17g2jJfuwMfHBMOJDplXfWINlm4JmhcUHf1OEuFoe0d4HhWPK50r+lXNDN3jRLvRbtOTJvwup3x3TQWoz8xLTbcG9rTVWOw3YCQ4uqBrh9Poe9Wg1R2Qg84I5C3H6wEIN0iRgluFHJpdOgIS14SY9NaffTWG9Q+7SaKYA+B8OdWrfp4RrLJxBc89KW5lhHffeUXLruwa4F7hJd+ZhyA29qlHwix3cHDSaxgfbG2dXbXv3H2C2F0LU27n+P/mgkzKTqibx9ydJNkG0uVYRbixejZgf+TJ3VPfnwMbdnCLUKvMydYWt50lDVx4+1N125+Rtieak74ACZZ2lesHeHuxoTJbRFNTtkofNKZWpGjCL5sPp/4eTmTyifTHTfVHEmllsEEQ8amUvnGX4sKDBCd3uOjQGV3IRnHtvoiWcxuVqlcoHSeAPxxCOBv+2uwbPUNIaU1qwIH5ps/vyYAh1sHr6YWXtU5NDnv3+8IToN/J8x9r5b9/GN+QXkoLdiqUXfCdQbQVPOcF4xeSceKw1l+UXayiV0BNjKT5PK+tHV3UtY4kKt8W3R4skLAAU0AaSlRnh3dtmK0eh5IKCogUt7D8xCoyTxxn9rcMneU0U4iPf6xzijhlSyAisX
    KEYCLOAK_DB_USERNAME: AgCV2IiVQPU0Ftq2UO/DSsTGAksg8qO9IUL4zddisGUaL9tY4qVCRneoFvW6V0VUL/EoHndei8mVC+D9mA+oFzyXqELMasU/WfnTacNxHnyLXcbEwJOW2JYewfrz1ZXjc2h9y846JcZ+XapHfVn4sNaltgUABPJ/8uFmumoMlRA+/cLPmSnw8WstchsHqdqX0IWcnV+Iw4MeKHl60vMdUVMeCKKtXX77+QO3ZBRex7W7rgvc/UtE/IfVFEJ21tDE6+AsCXLpbyupC0C6v1m5Bpb/PKmDWRMmuP/g5kuV/+daCZfw86nR3fFt/SKHAHPbiYv0m40CwsdBP4wBhd+rxWmqKdc+22/5m9gKrNxznxGY5xa34vmrZ9wOhbhSe35siho66GwzfIFnEp1/cHOD/VVU3sFfD31WxsOq3pQOPcHpuXtdieW/Woizjqxr571rBQt7VCGEcUV07q40rAZSzB/2Qw5XdfToJD2kSutlh+qeZqv9q75OZJi2RQNwNbGV178k6CGBRbb1AIjEYAoIJt9de4ODj1ogzmDyRrjq0T/+yCxHS98qXY5kJJeyQ5Ko+2Fqi0zicQDVeoGfhnLFtQi+vKQL/RGtrU+5BkWpRxRTIlRQ/dym6+A11/z2iwrQR0XqxW+mwCmFMGEgPKdi6TOatqyJ5yimh2RF9LOG4teXqh0oDnN4OTV1YfjDv4lBM3enEOZsT+X/FQ==
  template:
    metadata:
      name: keycloak-db-secrets
      namespace: belovr
