---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secrets
  namespace: belovr
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgChPEHb1kfh1O54lU/hJh/dUP0oTGTh9qh9BDn0UTddjM2F2sk4AkdXqXofiPwS7Z0poHDvo6f1vU2Fawur5fbvPlHw2K54g5aMd6VL3qajmHKyeXJ9q/a36jVqQi2ddY9VuyYo5AKkjIjiSGo0rnP+vqCD7XXeajmA6HcA9jndcvDnMlMMMZajnnr0dVZoOxYTqgc1Qeg80IG9hlEJ9fZLbWkdaIy0tTKaASDI/oLodwdH8m5RtzPnGPZ9r3QRl7L6kksMViJSATy3Ld5sOJgTikhnMi6qJXPDPx42a72fdUBJFsUe0sm7BRsSnBOurMMKnQen4AHUMFt/0pdeEJ58CmvSc/23Y2SbsvwPRw96aDBBT/4KQAjFgnXgNeEvf0J1pqnzoPxI3rHbf6i5UTl527pJThTt2hXA/HrTldH7nrG3OEu2vzIaVAQCwinz82CvqpIZms+f6UU/CsLg2oPf5mncp/MMghWbkWU2nhzDn3hT1M2Nrf/nFN++Fti8jNqAEBTwCXM0p0Tp+lRAPYdDP/aWaXciEif5hdyTxKnSolnJu8KHoAX8+GX4oJ+w1OzbL4A43ZlwFiVWgpKmxv+gfV0gPSbyf7fVypHT8Kdr8sbgGtDGeR0CFfe++U4+mCT9fA6PaXyIUXqMJDCCEB0L8Z9IcgT/RODX+AF4UuamNx306HdrJ4fIExMuejtid7+0Jn+AHmM6Mt1E6Ti6F3stIt4es84i43b4ZM/iWc6K8fCArMvEnVGmz4+IXIR6AjK7FaLRYujeE6mZPgSCS8Ro
  template:
    metadata:
      name: keycloak-admin-secrets
      namespace: belovr
