---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-auth-secrets
  namespace: belovr
spec:
  encryptedData:
    AUTH_KEYCLOAK_SECRET: AgCTTnH+t45pmliMBix3FxbjKpuACD1CpJlgywuNuPNMD5L6noGlyGcwL2Gxrclj3yRyGlogAhDRXK3siIhORc19iL7k4JujOWJ1l/OMhbgEglTbSkdJyXgeWdMp9Cf7c7PtU49I2DOlWi+22jV4sYDvDVBmf3H4IZccIAQ2C3918Xld5LIrmizVHWwV0WuhyfWSxe7ezmtKymEebHPta48X3VlfEKpfpYoEJIPVaSCXmWdxXZ2P6vN7JKZn0ufhc1SnM3Dx0U6L6gh9lf5VcQRRvBjhuKWU8IY+ZVK+xgL3jc9wxQdGLILsGE6IAm3/e7FYjlMRvu0F0QenjnEa0lGCUymUQx6kLEWwSCLGRTkAnFgknpENdIQvcMut8SKzjknpeKdsJc8zZ57o28OE5mttDJzj59rQnngNIGm5+cfEd1slutHZBaZ3j5BMgZ0rUXwE4M5+n3h58LTuERh6SiESsTkc2bYKQgnXNaWCAnslLOU8N1vG3nYzS+oQ3R2daXNfuzNrh+gNcp+op9wfGTtWeS53Pld12Wv18TXg2W8mEuPJxWCStDLzb92qAiI7GhiMs5sWZ+w/BLrVDp88zGpjtGRMKnHknLc6ya1efx1AYIJW91FQ2jXJCusCU1zxPmRS04geTtEo3/igUZppjn8mPXr85oPCX+gmliuIiv/XltbfIz089BWEt+/3nfJgii+iB5+VAO0lLfVvzkgfkLNjlY0ttAm9ib+mqYkvXSeZNA==
  template:
    metadata:
      name: keycloak-auth-secrets
      namespace: belovr
