apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

resources:
  - belovr-auth.sealed.yaml
  - keycloak-auth.sealed.yaml
  - content-cloudflare.sealed.yaml
  - payment-shared.sealed.yaml
  - rabbitmq.sealed.yaml
  - r2.sealed.yaml
  - user-db.sealed.yaml
  - chat-db.sealed.yaml
  - content-db.sealed.yaml
  - payment-db.sealed.yaml
  - keycloak-db.sealed.yaml
  - keycloak-admin.sealed.yaml
  - rabbitmq-infra.sealed.yaml
  - grafana-admin.sealed.yaml
