---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: payment-db-secrets
  namespace: belovr
spec:
  encryptedData:
    PAYMENT_DB_PASSWORD: AgA3+NtoLR/K2fMma6EaHiiO/yPR+a1YKmIBBg6wN9UrCthfJd46JCReoq1+dDARVAY+YpFd5i0/JcX1T1ykn2MEsCDEwMVuZhpS+n1uTZrSlIBYKaZu5Y1Myv7MrwnsZzudDpr6x2tiLBI0qsSRMJLWIXy+wcb7iFGh2j0rL2ltdFrBzgOzEq6On0CrO85LVFynicCmQBZtLbCcFhrjd+JaxZ/piifMgislTTSnAcspS/hthGD5FS59P158/6SKTmn6JWmaJUsj5CjgiqMAgX4kFpvy+uT0sPkeSVjYIS03hnXPcBctaaClfH+N9yCVgz49jEvNGJnK4UL8wS668TiCbI4Y1xfzToSyG+cTe2nK2VHN+2pa01LP5ltZzo/8KxZ4ShFvk6BPQDp0aijiPg+lpQ0OiHVHU4lfpfU/i+F3kM5C602aGHcMU8wYCDBSVFoh95D+Y+s15mpqoDp11SUrBlBbhXIekOg7z3ru2cvqulFkZNCTaGx2C6ZXngPoQBPn+C2fCkQ5drxfQkRnNTTbcaRzBttbWyR47rHw1BDb0yZb+zTtqi6Jsp8BEdgKXlzOrQTOBPLnGnQ88x8BHC5MEypyZrIMSFPb/1rx/rUAKQbZmV5CXKY4vbGRlHXM+Brz9HWUAazm2Udcj8iZOgBej9AYW8059HAlGxvYjRlyBeegne0CyvJquY3XJdBLUFBEhA+FkkOm/28u1oT7ndEv6qO+QIcI5pRPCqGwsqdX9g7kDnuhYlBxR20hUKSy6qK3Tjj50DWvzWeHx5eL9MeA
  template:
    metadata:
      name: payment-db-secrets
      namespace: belovr
