---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: payment-shared-secrets
  namespace: belovr
spec:
  encryptedData:
    PAYMENT_INTERNAL_API_SECRET: AgBqSQ0OB58iQMu2DVio3j4f1VxNLQnH2yty/MQQoa/RnMejaKqXw9RYJ2FBJz4vql+NFIXrNX5eQGcvsJcKTRW+rt6ax+kwjHB0wQg3IwKVU73hEVVee4k/sqtrbmgcLsqx3BHLU8u9Vy5+k55oysGDa2KAAimVKCSv1FVUDFrPizmtt6Q/xbuOSMzT2j6RHbf0Erq4S1/wI2bD5R8+R3bDbwgYyv460AnEHbvekf4b3tWxVKVIdHfcgbflvdu1iuwYP6Rz+xvRdVijQv5YBal6QHyrL3XQ0zPDLtDeWa/adAdTZFLEa8lSF32CXlO/epe9+gIj5368wUs6MMD63ZW4cpjUOR1GZ7kSOCWk9AW3S3M0aVQK+zG6RSyUTz5zBcSaYTHjmMwYMmMacY1yvUh4GBKfi9cBqs3hJNzUFyvBX0qSUQ5QV9PMHmgdvre4i1vs29pCirM7hmaQmCOsVmTvb1UIvLU51XbUdSOURArruQQcaceXVf+a9wG/9h4JWXUFVcM34mbBFPlrrQuALeUxHNHQSu3IQDnZVDwXNGT+ylCLD75rINf8sPBRuzeanrt4Sd7KyZLbT59Xxp1pPvooivIqfIy/VjJlmAke0h7gv8NGv6u+sqZjTRdMGXg3OuoMh17mt1UMmuwegQr+gy+x6DxHWR3u6EH4L6SnqBw6nrMA/LA4H2cQCTVtivc6TuCD20WmsEdIc+FmVltcSr1l8EP6sVwEyuMMNNv9/hXtLtY+N+o4lSvD9sxVLxZiNUSaVP8ojZcLJUQE5W5BOMod
  template:
    metadata:
      name: payment-shared-secrets
      namespace: belovr
