---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: belovr-r2-secrets
  namespace: belovr
spec:
  encryptedData:
    R2_ACCESS_KEY: AgBYjKUGsM+6kEuV4wF6k75v9NLQeeB8YU7Ts6lYVQoUVToVfOMaOfpHP6/2SdYxpoSX/gHQT8wpsY3Li7tMIp1rVu84ou8r/Rk/vz0deeJJAdztI2sqvthlwYF3X3BcJRrM99dw54c2wFupQUwBVcgDpp2oPR6Xb+RRAbF2hOkkI4F3Z/P9v3tz0LCUhvqpSQSMyA2tLdCGpUy9otPR56jDYxscYZ/sAPsRWBZTbR4fodhkQU8/SbqLZonYI+Gzgdy6LwYPE+PugXVkkJfgnwqiv0TShrHhO4Id9daKgC2yx4vuDn5Kh738Be+uNsTgb8mfAtHdPbHxyi/Mkin97fyuW8PSVwHeXIhqy9tDxCeuHP3QFcyVv2aWBy03rCBzleG0v2qa8Dcn7p58F9JXR2HbTEqkMXMC2BrCvERvgAlxOFMQoGOtJQ6KXFne+VxCRYgr3SpjxxCyehdfI6aqaO45SEozL37a83vslouXipgVIFXrZvqV01HDz/XhGdiLeirrZCXlsfuVD6menNLzy03G9SL74zVAhuyMKDExxL4econte943VszdPqCtZhGyjfh1eFlpjJcswIOy2qNr6cUbwcWAWMrc/JPwjTOw5skDRePn/YqWyV7Dwu7rNGC2BCo43veCN4vbdND2Za/mEVXwIHYHZtRAORzi6dGd8f2TdscELw/79ZV6PMlEAex30RpCIcaPE3HMV9Qzg2in9RZs6faj4PvtKbMBKF430LRVXw==
    R2_SECRET_KEY: AgCj+qKsFNx5HfPP5F2e4ATQLcZ9zkfiyQWGwNbCMwDBvQJWFypxDvldxP7FXcJrzP3vSmTVi8gjr5wSJcsPE93QKffTWE4Tu3/R+Dc+C8xLzMHWP8avgd3UvnYfOV/WSs7VvY8I9AboSNrtwkU6c8lO5f33Rw/QRjKp8fKNc5o6Z9TOpKJtzT+MY8jlU41I5z5YWdNGJSmtiIybwGS6u8AD/+SEiD+/BF+g9biT8Zg+BVUkB+2zs0We4oP0mqfzVzjl6b3JQkBOpfMkMgbhSqePyqwSz76Sy/kV5KQTDQVmcRWLdscModjxdufJ9YyXP7HgJ0fvJMcSFMB/VvJAF0V6ohrKbRiTypm51IWmPZ9LPiDojOlqEPEFknXzklaAOvLgGVsYVnrwwZCujgE6CcxGAPGqqXqNPymN52h21eLPjwmidk2x6hqYR1XBE7+rBj09hdY/Go+0D6IObgJ9Sj1PY0dPOkzNBlDq8CiFtMXIvEJFoBqAQtyek6saUg5e5RWrOBXVgC/ub489bx/ZIADrVEfDzqiaphGwoPugnTDF2mZxdhVXt7wI8Lr0aPGF3CaTTGck2yEn0t06Z9VEwICAMlKIJWkrIn/4S8N3XvdAa87YpjW2mvYS51n9czy3jlZyTptASx56RyCZEVXOGec30+CNNMd2Rp+a43bJ3MiS0rRHEK2BEYIsturBvpKFI3nNo91V/dToOQHb29M4CQUXbO5SDWoo6T+iILvgZ8+P0yg70RUDNNbUpaCX4uaxDxH8Pjq8RKP1fzOX/CaMx3E5
  template:
    metadata:
      name: belovr-r2-secrets
      namespace: belovr
