---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: belovr-rabbitmq-secrets
  namespace: belovr
spec:
  encryptedData:
    AMQP_URL: AgCVd9/6YOAD2IaREGXTmMWifh3uiScSLeMb2JzOqfRrF4pyniy1azbneyBmYLFhaHUnL0+QQx9P/NOf6LBirAcJAX+8egzgDWo3zAJJHbYKE4l7zDelJoFXxWKi9FBH0xAFTIQO60CQ70k+Zd4Ou+pLKFyAFpS5esCfLlN0p1bSZY9G7Kd1o2fmoSDLcLaQIJIapXnkcoCtq49bgZPbtPIgNuyCE8HmC4UCAwcDzecx1XJe5pGFjEP4XAUZvB8xYFmX+X99vObl2Gpm73RT02zTTSrpAeVk39RNEWZswQdW5Ev2JRW72MSI+c6ovzM6NP5ju/EA6RIIPb/GLXgiMJzJ5mSO2znsAJ3P6OkMDUcEIO9YatilL856cn98frdxgkCMgE40xfsEVr8lR318GK0kSugysMawQtEOt2nHBrVNo79BC6X5QAJV293ffn76odAcuU4IO4CpPNvFYj3gzfriFUxZdiNKfaRwNRKr4leMZBB1RyKhWugHF+RzRabOh3CIgTsb/n1GshpJOVPUpMY+XmtzBMjyvMx1vjFiGwsaP83zZLytQF6T7C7myMkZk80QjV9HFI8PRWX/7EN8yeLVFtSgCiVys+XElIeXzQQ3RlwZjdHd6rncg8vmkhaBu3wuD3P3QE41BK67YFBEeEpo2HBa/c1EvHwECxkDQN38OIJdXazdlyCL/TsDd1cnTmc0Ql2HNedLXf3wSHMVn2WJu+C1QKArWVHgn2pJmVqiJSZ5jAV9dYHBKxOKiThpgmsbrXuuerACnO7h7CDckWoyV5B8
  template:
    metadata:
      name: belovr-rabbitmq-secrets
      namespace: belovr
