---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: belovr-rabbitmq-secrets
  namespace: belovr
spec:
  encryptedData:
    AMQP_URL: AgBFlNNBN+zu4gRU8eeOj5Ii3IinD5/fsgeDmfeGfHC0ltMYbivFZTvKI+DdBqOGp3kLOpivtsAEVIUiTWpzKUZzFM3poKr+RkpXK7OO7nIGWCOHu/X0b3AE3zt4sbkbMBiG9DsCqfq60stq85vDEFuyYq3kr9juPs0yQTRClWrbROkDnAXvnAagyGmTBrO/yf8X808JYqZebubfycAxW07eLNgr/PG9tqTXOdEJfX+P5MRWV/N+IizQ+zFfrTgfB7q83YPSsmEhxxdXwLEpnPOmfuK/6tbf+k3HZbpNNtHDRyGEnEuBBFFrFdEo/tWMVaaLRPPCnfiWATyrSgWfgmO+jkjBCgJgeSp9ZKdBsdYqWN6Abk5P/FkNK6+8kZYmrBhKytEKTKT7IkFcwPt5IozsLE+DFZd06ATEn9ifiLgWQN2XH2XzGCS0ENFvzr7hrdPhgkltZihPYs9eA3vZn2aHXcxkVHiqhGV1tnTd/IDPse+kyd9ufyiqwCUfu7XYrQ0bv3Zb28M+opoaiDiMctCWajccgSSyk6mTj/9hUjOvT4uZruU5U2pT+VORDL1jt9NA2ofo7o+xB1SP9IkwRXgIDB8Tlij84q9SyuY8HEsVebSeSQIPUWHjhFcqUucpnh321/Hgr4/UHX5gupiv5Bh86mYjTdBoLF49pax6jSaQM7/JabJVpbhH+zUDp3SBobxpOPabcgHooMSV9b/WAA/im3u4r3n0CwBKGdcpdd2tJrxlgHhBVAeXW6FfbBPmN+R3iTQslNB9srIXX+1z8l1FjARWwSOI84VHYNPwdKg6yyGrjryaz5fKWEku6V+u42EC1FQ6y2ZEw7yF9M6FQ0z9hCZcj3a7hA==
  template:
    metadata:
      name: belovr-rabbitmq-secrets
      namespace: belovr
