---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-db-secrets
  namespace: belovr
spec:
  encryptedData:
    APP_DB_PASSWORD: AgBGVNeKWDakk8MoFSO26PecWPlmvy+pxtQ7lm+h4SAr6jW1ktQ6qsjXsnE5hTvEVoTkHqY3vCMi47lb3uYt3z+Kjzc8LTcSgFp43fu3vUP63EgbhF1PTz7/bAKsPk+iiXpYxjJG65SMMthM36LKFSFu9cLla/hfz40wi+0CxWqqtZviaK+e1zjjVTOXxIihvDDRPtMvdld+ZgG/xJtCVM/ssNBrv+ivDsC/pugbrq6Ayd3Fe8NPVE9kalZn1xgaa4FheWSoZh5sz6LRv0chYlXfvXuIXZXc3aQx4/0irN5cA6cYiF/avaHKGziSVYAIHG/hTum5BHJA5GlzzqREYewHBPiTXIPtF3G6IFmsHtVJfc/cn1UVMSvxjSQ7tZMP5r7P8yzglzR0oldTuTwRxW6svkVWGUc2i+8kZScQ/Eg9Gn/e6lF/bTWAWioEFqrVz3hlFGf7+8cxnFRTg3urmG8w/WMEppscdarrIM4twNo0qxk+t+qVPSZAFfJ8g84So1LjCUAbKKrskgUavKbVqxMPvNPQYn1+3Yrwl6gKirdkjDMcn3BVqyqGqlUJ+sAEcuifsPDGdXoQd0sw5B7A3voKv9tHv5KaT3aLJAa1Du+eILLRQ53b16Ylic3y+xqAdbEuKMRzJWhW8FC76kVyobPfqSSMscGADn9Corbl68ZoPQ964or7elEXgjQDcJyyjdbBUyXRz8VflhBeKJDyGAYmSBb4EQ4r3N11A31fYebLDOUE/n7Ej+/U1osIQTS3NKUj3gwwAPVZn+81MOqnc0gn
  template:
    metadata:
      name: user-db-secrets
      namespace: belovr
