apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-db
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: belovr-platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "18.1.8"
    helm:
      releaseName: chat-db
      valuesObject:
        auth:
          username: chat
          password: chatpass
          database: chat
        primary:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: microk8s-hostpath
  destination:
    server: https://kubernetes.default.svc
    namespace: belovr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
