apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: content-db
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: belovr-platform
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
    targetRevision: "18.1.8"
    path: .
    helm:
      releaseName: content-db
      valuesObject:
        auth:
          username: content
          password: contentpass
          database: content
        primary:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: microk8s-hostpath
  destination:
    server: https://kubernetes.default.svc
    namespace: belovr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
