apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: belovr-platform
  source:
    repoURL: oci://ghcr.io/cloudpirates-io/helm-charts/keycloak
    targetRevision: "0.8.7"
    path: .
    helm:
      releaseName: keycloak
      valuesObject:
        extraInitContainers:
          - name: add-keycloakify-theme
            image: corsaire300iq/custom-theme-keycloak:latest
            imagePullPolicy: Always
            command:
              - sh
              - -c
              - |
                echo "Installation du JAR Keycloakify..."
                cp /opt/keycloak/providers/*.jar /target/providers/
            volumeMounts:
              - name: keycloak-providers
                mountPath: /target/providers
        preserveThemes: true
        preserveProviders: false
        global:
          imagePullSecrets:
            - dockerhub-secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        keycloak:
          adminUser: admin
          adminPassword: adminpass
          hostname: sso.belovr.com
          httpEnabled: true
          production: true
          hostnameStrict: true
          proxyHeaders: xforwarded
        database:
          type: postgres
          host: keycloak-db-postgresql.belovr.svc.cluster.local
          port: "5432"
          name: keycloak
          username: keycloak
          password: keycloakpass
        postgres:
          enabled: false
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
            - host: sso.belovr.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - sso.belovr.com
              secretName: belovr-app-tls-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: belovr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
