apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../argocd/project
  - ../../infrastructure/namespace
  - ../../infrastructure/network/base
  - ../../infrastructure/observability/base
  - ../../services/overlays/prod
