apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: belovr-root
  namespace: argocd
spec:
  project: belovr

  # Le cluster et namespace où Argo CD appliquera les manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Source du chart racine (ton dossier argocd/)
  source:
    repoURL: https://github.com/nicolasdemol/belovr-cluster.git
    path: argocd
    targetRevision: main
    helm:
      releaseName: belovr-root
      valueFiles:
        - values.yaml

  # Politique de synchronisation (GitOps complet)
  syncPolicy:
    automated:
      prune: true # Supprime les ressources obsolètes
      selfHeal: true # Corrige les écarts avec Git
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
