apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
spec:
  source:
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: rabbitmq.lab.belovr.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - rabbitmq.lab.belovr.com
              secretName: belovr-app-tls-secret
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
