apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nicolasdemol/belovr-cluster.git'
    targetRevision: main
    path: helm/databases/chat-postgres
    helm:
      releaseName: chat-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: belovr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
