apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "35"
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: belovr
    belovr.io/environment: prod
data:
  PORT: "3001"
  AUTH_KEYCLOAK_TIMEOUT_MS: "9000"
  LOG_SERVICE_NAME: auth
