apiVersion: v1
kind: ConfigMap
metadata:
  name: belovr-common-config
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "35"
  labels:
    app.kubernetes.io/part-of: belovr
    belovr.io/environment: prod
data:
  NODE_ENV: production
  CORS_ORIGIN: https://app.belovr.com
  AUTH_KEYCLOAK_ID: belovr-web
  AUTH_KEYCLOAK_ISSUER: https://sso.belovr.com/realms/belovr
  REDIS_HOST: redis-master.belovr.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_URL: redis://redis-master.belovr.svc.cluster.local:6379
  LOG_LEVEL: info
  LOG_PRETTY: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector-gateway.observability.svc.cluster.local:4318
