apiVersion: v1
kind: ConfigMap
metadata:
  name: content-config
  namespace: belovr
  annotations:
    argocd.argoproj.io/sync-wave: "35"
  labels:
    app.kubernetes.io/name: content
    app.kubernetes.io/part-of: belovr
    belovr.io/environment: prod
data:
  PORT: "4100"
  CONTENT_DB_TYPE: postgres
  CONTENT_DB_HOST: content-db-postgresql.belovr.svc.cluster.local
  CONTENT_DB_PORT: "5432"
  CONTENT_DB_USER: content
  CONTENT_DB_NAME: content
  CONTENT_DB_SYNC: "false"
  CONTENT_DB_LOGGING: "false"
  CF_ACCOUNT_ID: e42b1dcd7b3bdabf10bb3c3afeb1828f
  CF_NAMESPACE_ID: 93004e80b07a4464bb938699490f315d
  R2_ENDPOINT: https://e42b1dcd7b3bdabf10bb3c3afeb1828f.r2.cloudflarestorage.com
  R2_RAW_BUCKET: belovr-raw
  R2_TRANSCODED_BUCKET: belovr-dash
  R2_IMAGE_BUCKET: belovr-image
  R2_PUBLIC_TRANSCODED: https://media.belovr.com
  R2_PUBLIC_IMAGES: https://images.belovr.com
  LOG_SERVICE_NAME: content
