apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common.yaml
  - ai.yaml
  - auth.yaml
  - chat.yaml
  - content.yaml
  - image.yaml
  - payment.yaml
  - realtime.yaml
  - social.yaml
  - user.yaml
  - video.yaml
  - web.yaml
