apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-db
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://qdrant.github.io/qdrant-helm
    chart: qdrant
    targetRevision: "1.16.0"

    helm:
      releaseName: ai-db
      valuesObject:
        # -------------------------------------------------------------------------------------
        # QDRANT CONFIGURATION
        # -------------------------------------------------------------------------------------
        config:
          log_level: INFO
          storage:
            on_disk: true
            storage_path: "/qdrant/storage" # default safe path
          cluster:
            enabled: false # Standalone mode for now
          snapshots:
            enabled: true

        # -------------------------------------------------------------------------------------
        # PERSISTENCE
        # -------------------------------------------------------------------------------------
        primary:
          persistence:
            enabled: true
            size: 5Gi
            storageClass: microk8s-hostpath

        # -------------------------------------------------------------------------------------
        # SERVICE
        # -------------------------------------------------------------------------------------
        service:
          ports:
            http:
              port: 6333
              checksEnabled: true
            grpc:
              port: 6334
              checksEnabled: false
            p2p:
              port: 6335
              checksEnabled: false

        # -------------------------------------------------------------------------------------
        # RESOURCES (recommended for Qdrant)
        # -------------------------------------------------------------------------------------
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 2Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
