apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-postgres
  namespace: belovr
spec:
  project: belovr

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
    targetRevision: "18.1.8"
    path: .
    helm:
      valuesObject:
        auth:
          username: chat
          password: chatpass
          database: chat
        primary:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: microk8s-hostpath

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
