# LE POD SUPPORT (Un seul suffit pour tout le cluster)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: belovr-dev-hub
  namespace: belovr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belovr-dev
  template:
    metadata:
      labels:
        app: belovr-dev
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
---
# LE SUPER-SERVICE (Un seul objet pour tous tes ports)
apiVersion: v1
kind: Service
metadata:
  name: belovr-dev-service
  namespace: belovr
spec:
  selector:
    app: belovr-dev
  ports:
    - { name: frontend, port: 3000, targetPort: 3000 }
    - { name: auth, port: 3001, targetPort: 3001 }
    - { name: user, port: 4000, targetPort: 4000 }
    - { name: content, port: 4100, targetPort: 4100 }
    - { name: chat, port: 4200, targetPort: 4200 }
    - { name: social, port: 4300, targetPort: 4300 }
    - { name: payment, port: 4400, targetPort: 4400 }
    - { name: realtime, port: 4500, targetPort: 4500 }
    - { name: ia, port: 8080, targetPort: 8080 }
---
# L'INGRESS UNIFIÉ (Version sécurisée pour App Router)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: belovr-unified-ingress
  namespace: belovr
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_server_name on;
      if ($request_uri ~* "^/video") { set $proxy_upstream_protocol https; proxy_set_header Host cdn.belovr.com; }
      if ($request_uri ~* "^/images") { set $proxy_upstream_protocol https; proxy_set_header Host images.belovr.com; }
spec:
  ingressClassName: nginx
  tls:
    - hosts: [dev.192.168.1.12.nip.io]
      secretName: belovr-app-tls-secret
  rules:
    - host: dev.192.168.1.12.nip.io
      http:
        paths:
          # AUTH : On garde /srv/auth car Next-Auth est rigide là-dessus
          - {
              path: /srv/auth,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 3001 } },
                },
            }

          # AUTRES SERVICES : On utilise /srv/ pour éviter le conflit avec app/api/
          - {
              path: /srv/user,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 4000 } },
                },
            }
          - {
              path: /srv/content,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 4100 } },
                },
            }
          - {
              path: /srv/chat,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 4200 } },
                },
            }
          - {
              path: /srv/social,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 4300 } },
                },
            }
          - {
              path: /srv/payment,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 4400 } },
                },
            }
          - {
              path: /srv/realtime,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 4500 } },
                },
            }
          - {
              path: /srv/ia,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 8080 } },
                },
            }

          # MEDIAS & FRONTEND
          - {
              path: /video,
              pathType: Prefix,
              backend:
                { service: { name: proxy-cdn-belovr, port: { number: 443 } } },
            }
          - {
              path: /images,
              pathType: Prefix,
              backend:
                {
                  service: { name: proxy-images-belovr, port: { number: 443 } },
                },
            }
          - {
              path: /,
              pathType: Prefix,
              backend:
                {
                  service: { name: belovr-dev-service, port: { number: 3000 } },
                },
            }
