# LE POD SUPPORT & LE SUPER-SERVICE (Inchangés, c'est parfait)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: belovr-dev-hub
  namespace: belovr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belovr-dev
  template:
    metadata:
      labels:
        app: belovr-dev
    spec:
      containers:
        - { name: pause, image: registry.k8s.io/pause:3.9 }
---
apiVersion: v1
kind: Service
metadata:
  name: belovr-dev-service
  namespace: belovr
spec:
  selector: { app: belovr-dev }
  ports:
    - { name: frontend, port: 3000, targetPort: 3000 }
    - { name: auth, port: 3001, targetPort: 3001 }
    - { name: user, port: 4000, targetPort: 4000 }
    - { name: content, port: 4100, targetPort: 4100 }
    - { name: chat, port: 4200, targetPort: 4200 }
    - { name: social, port: 4300, targetPort: 4300 }
    - { name: payment, port: 4400, targetPort: 4400 }
    - { name: realtime, port: 4500, targetPort: 4500 }
    - { name: ia, port: 8080, targetPort: 8080 }
---
# L'INGRESS LOCAL (Ton PC / Telepresence)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: belovr-local-ingress
  namespace: belovr
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Nettoie le préfixe /srv/ avant d'envoyer à ton PC (évite les 404 NestJS)
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts: [dev.192.168.1.12.nip.io]
      secretName: belovr-app-tls-secret
  rules:
    - host: dev.192.168.1.12.nip.io
      http:
        paths:
          # On capture tout ce qui est après /srv/xxx/ pour le mettre dans $1
          - path: /srv/auth/(.*)
            pathType: ImplementationSpecific
            backend:
              { service: { name: belovr-dev-service, port: { number: 3001 } } }
          - path: /srv/user/(.*)
            pathType: ImplementationSpecific
            backend:
              { service: { name: belovr-dev-service, port: { number: 4000 } } }
          - path: /srv/content/(.*)
            pathType: ImplementationSpecific
            backend:
              { service: { name: belovr-dev-service, port: { number: 4100 } } }
          # ... Ajoute les autres /srv/ ici sur le même modèle ...

          # FRONTEND (Sans rewrite, direct à la racine)
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              { service: { name: belovr-dev-service, port: { number: 3000 } } }
---
# LES SERVICES EXTERNES (Cloudflare)
apiVersion: v1
kind: Service
metadata:
  name: proxy-cdn-belovr
  namespace: belovr
spec:
  type: ExternalName
  externalName: cdn.belovr.com
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-images-belovr
  namespace: belovr
spec:
  type: ExternalName
  externalName: images.belovr.com
---
# L'INGRESS MÉDIAS (Tunnel vers Cloudflare)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: belovr-proxy-ingress
  namespace: belovr
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_verify off;
      proxy_ssl_server_name on;
      proxy_ssl_name cdn.belovr.com;
      proxy_set_header Host cdn.belovr.com;

      # Forcer le Referer pour éviter les blocages Cloudflare
      proxy_set_header Referer https://cdn.belovr.com/;
      proxy_set_header Origin https://cdn.belovr.com;

      # 🚨 Headers CRUCIAUX pour le streaming (CORS & Byte Range)
      proxy_hide_header 'Access-Control-Allow-Origin';
      proxy_hide_header 'Access-Control-Expose-Headers';

      add_header 'Access-Control-Allow-Origin' '*' always;
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS, HEAD' always;
      add_header 'Access-Control-Allow-Headers' 'Range, Content-Type, Authorization' always;
      add_header 'Access-Control-Expose-Headers' 'Content-Length, Content-Range' always;

      # Gérer les requêtes OPTIONS (Preflight) que les lecteurs DASH envoient
      if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' '*';
          add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS, HEAD';
          add_header 'Access-Control-Allow-Headers' 'Range, Content-Type, Authorization';
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts: [dev.192.168.1.12.nip.io]
      secretName: belovr-app-tls-secret
  rules:
    - host: dev.192.168.1.12.nip.io
      http:
        paths:
          - path: /videos/(.*)
            pathType: ImplementationSpecific
            backend:
              { service: { name: proxy-cdn-belovr, port: { number: 443 } } }
