# 1. LE CLUSTER ISSUER (Global)
# Utilise ton Token API Cloudflare stocké dans le namespace cert-manager
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-issuer
spec:
  acme:
    email: nyco.demol@gmail.com # 👈 Remplace par ton email réel
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
# 2. LE CERTIFICAT WILDCARD
# Un seul certificat pour protéger tous les sous-domaines *.belovr.com
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: belovr-wildcard-tls
  namespace: belovr
spec:
  secretName: belovr-app-tls-secret
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  commonName: "*.belovr.com"
  dnsNames:
    - "*.belovr.com"
    - "belovr.com"
---
# 3. LE POD DE SUPPORT (HUB)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: belovr-dev-hub
  namespace: belovr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belovr-dev
  template:
    metadata:
      labels:
        app: belovr-dev
    spec:
      containers:
        - { name: pause, image: registry.k8s.io/pause:3.9 }
---
# 4. LE SUPER-SERVICE (Vers Telepresence / Local)
apiVersion: v1
kind: Service
metadata:
  name: belovr-dev-service
  namespace: belovr
spec:
  selector: { app: belovr-dev }
  ports:
    - { name: frontend, port: 3000, targetPort: 3000 }
    - { name: auth, port: 3001, targetPort: 3001 }
    - { name: user, port: 4000, targetPort: 4000 }
    - { name: content, port: 4100, targetPort: 4100 }
    - { name: chat, port: 4200, targetPort: 4200 }
    - { name: social, port: 4300, targetPort: 4300 }
    - { name: payment, port: 4400, targetPort: 4400 }
    - { name: realtime, port: 4500, targetPort: 4500 }
    - { name: ia, port: 8080, targetPort: 8080 }
---
# 5. SERVICES EXTERNES (Cloudflare)
apiVersion: v1
kind: Service
metadata:
  name: proxy-cdn-belovr
  namespace: belovr
spec:
  type: ExternalName
  externalName: cdn.belovr.com
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-images-belovr
  namespace: belovr
spec:
  type: ExternalName
  externalName: images.belovr.com
---
# 6. L'INGRESS MULTI-SERVICES (SSL Wildcard + Routing)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: belovr-main-ingress
  namespace: belovr
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://app.belovr.com"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_verify off;
      proxy_ssl_server_name on;
      proxy_set_header Referer https://cdn.belovr.com/;
      # Headers CORS indispensables pour le streaming iOS
      add_header 'Access-Control-Allow-Origin' 'https://app.belovr.com' always;
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS, HEAD' always;
      add_header 'Access-Control-Allow-Headers' 'Range, Content-Type, Authorization' always;
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["*.belovr.com", "belovr.com"]
      secretName: belovr-app-tls-secret
  rules:
    # --- APP (Frontend + Vidéos) ---
    - host: app.belovr.com
      http:
        paths:
          - path: /videos
            pathType: Prefix
            backend:
              service: { name: proxy-cdn-belovr, port: { number: 443 } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: belovr-dev-service, port: { number: 3000 } }

    # --- SERVICES API ---
    - host: auth.belovr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: belovr-dev-service, port: { number: 3001 } }

    - host: user.belovr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: belovr-dev-service, port: { number: 4000 } }

    - host: content.belovr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: belovr-dev-service, port: { number: 4100 } }

    - host: chat.belovr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: belovr-dev-service, port: { number: 4200 } }

    - host: realtime.belovr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: belovr-dev-service, port: { number: 4500 } }

    - host: ia.belovr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: belovr-dev-service, port: { number: 8080 } }
