apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: belovr
spec:
  project: belovr

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/keycloak
    targetRevision: "25.2.0"
    path: .
    helm:
      valuesObject:
        global:
          security:
            allowInsecureImages: true

        image:
          registry: docker.io
          repository: bitnamilegacy/keycloak
          digest: "sha256:da3df0976a9f9a664bdbde6cb5308b78f03ac94d0abf33b2df355bbb06cbc5b9"

        auth:
          adminUser: admin
          adminPassword: "adminpass"

        # 🚀 Activation de l'Ingress
        ingress:
          enabled: true
          hostname: "keycloak.192.168.1.12.nip.io"

        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnamisecure/postgresql
            digest: "sha256:14aa30df4c41d43590a0ae59b1963522f5e4344bedda67e1f2e423ea8267c115"
          auth:
            username: keycloak
            password: keycloakpass
            database: keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
