apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/cloudpirates/keycloak
    targetRevision: "0.8.7"
    path: .
    helm:
      valuesObject:
        keycloak:
          adminUser: admin
          adminPassword: adminpass
          hostname: keycloak.192.168.1.12.nip.io
          httpEnabled: true
          production: false
          proxyHeaders: xforwarded
          hostnameStrict: false
          hostnameStrictHttps: false

        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          hosts:
            - host: keycloak.192.168.1.12.nip.io
              paths:
                - path: /
                  pathType: Prefix
          tls: [] # en HTTP pour l’instant

        database:
          type: postgres
          host: keycloak-db-postgresql.belovr.svc.cluster.local
          port: "5432"
          username: keycloak
          password: keycloakpass
          name: keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
