apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/keycloak
    targetRevision: "25.2.0"
    path: .
    helm:
      valuesObject:
        global:
          security:
            allowInsecureImages: true

        image:
          registry: docker.io
          repository: bitnamilegacy/keycloak
          digest: "sha256:da3df0976a9f9a664bdbde6cb5308b78f03ac94d0abf33b2df355bbb06cbc5b9"

        auth:
          adminUser: admin
          adminPassword: "adminpass"

        ingress:
          enabled: true
          hostname: "keycloak.192.168.1.12.nip.io"

        postgresql:
          enabled: false

        externalDatabase:
          host: keycloak-db-postgresql.belovr.svc.cluster.local
          user: keycloak
          password: keycloakpass
          database: keycloak
          port: 5432

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
