apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/cloudpirates/keycloak
    targetRevision: "0.8.7"
    path: .
    helm:
      valuesObject:
        keycloak:
          adminUser: admin
          adminPassword: adminpass

          hostname: sso.belovr.com
          httpEnabled: true
          production: true
          hostnameStrict: true
          proxyHeaders: "xforwarded"

        database:
          type: "postgres"
          host: "keycloak-db-postgresql.belovr.svc.cluster.local"
          port: "5432"
          name: "keycloak"
          username: "keycloak"
          password: "keycloakpass"

        postgres:
          enabled: false

        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
            - host: sso.belovr.com
              paths:
                - path: /
                  pathType: Prefix
          tls: 
            - hosts:
                - keycloak.belovr.com
              secretName: belovr-app-tls-secret

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
