apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/cloudpirates/rabbitmq
    targetRevision: "0.7.8"
    path: .
    helm:
      valuesObject:
        # -------- AUTH --------
        auth:
          enabled: true
          username: rabbitmq
          password: "rabbitmqpass"
          erlangCookie: "myerlangcookie123"

        # -------- PERSISTENCE --------
        persistence:
          enabled: true
          storageClass: microk8s-hostpath
          size: 2Gi

        # -------- OPTIONAL: ADD UI INGRESS --------
        ingress:
          enabled: true
          hostname: "rabbitmq.192.168.1.12.nip.io"

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
