apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/rabbitmq
    chart: rabbitmq
    targetRevision: "16.0.14"
    helm:
      valuesObject:
        global:
          security:
            allowInsecureImages: true

        image:
          registry: docker.io
          repository: bitnamisecure/rabbitmq
          digest: "sha256:6b1bc580ac0fc5cc3581127c1599268af91e642181d43bd78f5ec4bc2fa4753d"

        auth:
          username: rabbitmq
          password: "rabbitmqpass"
          erlangCookie: "myerlangcookie123"

        persistence:
          enabled: true
          storageClass: microk8s-hostpath
          size: 2Gi

        service:
          type: ClusterIP
          ports:
            amqp: 5672
            manager: 15672

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
