apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: belovr

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/redis
    targetRevision: "23.2.12"
    path: .
    helm:
      valuesObject:
        architecture: standalone
        auth:
          enabled: true
          password: redispass123

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr-preprod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
