apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-postgres
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
    targetRevision: "18.1.8"
    path: .
    helm:
      valuesObject:
        auth:
          username: user
          password: userpass
          database: user
        primary:
          persistence:
            enabled: true
            size: 2Gi
            storageClass: microk8s-hostpath

          service:
            type: NodePort
            ports:
              postgresql: 5432
            nodePorts:
              postgresql: "30431"

  destination:
    server: https://kubernetes.default.svc
    namespace: belovr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
