apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../services/overlays/prod/secrets
labels:
  - pairs:
      belovr.io/environment: prod
      belovr.io/tier: secrets
