apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: belovr-prod-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: belovr-platform
    belovr.io/environment: prod
    belovr.io/tier: observability
spec:
  project: belovr-platform
  source:
    repoURL: https://github.com/nicolasdemol/belovr-cluster.git
    targetRevision: main
    path: environments/prod/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
